# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdbd1da06289d346d9909f6924db8902d870f3b25621fc79c745440a244dde98fbfce9085dcba162e2e4007cc2837aed0757427001e103484688b2101bf768b1

test:
  secret_key_base: 65e1a638a841d7e16dc2cb1f448c86a120538b4f8c76d9b5c0178111bbef01ddcf67ee21af365812a70c938d77ec611f4065d9f57e976a19310ede53a4bae386

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
